#! /bin/bash
echo "Running shell ${BASH_VERSION}"
#python3 setup.py clean
python3 -m build
# python3 setup.py bdist_wheel
# python3 setup.py pytest
last=`ls -t dist/* | head -1`
echo "Last version is: $last"
pip install "$last" --upgrade
